[[MAGEMin]]
arch = "aarch64"
git-tree-sha1 = "4003fc45cc2136412748ec908ebce303288c166e"
libgfortran_version = "5.0.0"
os = "macos"

    [[MAGEMin.download]]
    sha256 = "863be6959bd69ce1ca3dbcbc54d962d2a8cbce401777eaa81452acffc2930f7d"
    url = "https://github.com/JuliaBinaryWrappers/MAGEMin_jll.jl/releases/download/MAGEMin-v1.8.6+0/MAGEMin.v1.8.6.aarch64-apple-darwin-libgfortran5.tar.gz"
[[MAGEMin]]
arch = "aarch64"
git-tree-sha1 = "ebaccb513efb95c668777b48d3ceb5ed4dd7447d"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MAGEMin.download]]
    sha256 = "2283197e8c4ff1eb2e5fe684abe2fc7375ce1a41194f76af74f6632c1d276b26"
    url = "https://github.com/JuliaBinaryWrappers/MAGEMin_jll.jl/releases/download/MAGEMin-v1.8.6+0/MAGEMin.v1.8.6.aarch64-linux-gnu-libgfortran5.tar.gz"
[[MAGEMin]]
arch = "aarch64"
git-tree-sha1 = "ca18357573d081b420e687df0383bdef489e7303"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MAGEMin.download]]
    sha256 = "207bb9a66387c14a1688459425ca6e11b5cfe565bfec2ebfa35239632da45859"
    url = "https://github.com/JuliaBinaryWrappers/MAGEMin_jll.jl/releases/download/MAGEMin-v1.8.6+0/MAGEMin.v1.8.6.aarch64-linux-musl-libgfortran5.tar.gz"
[[MAGEMin]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "52ad18f6c14b0aedf3d8a7f1aaf98b8dce4128f1"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MAGEMin.download]]
    sha256 = "4e7712d3272bdf39aca16451a1950d9ce8dceb9502c6e3cd4b772c324fffd3b7"
    url = "https://github.com/JuliaBinaryWrappers/MAGEMin_jll.jl/releases/download/MAGEMin-v1.8.6+0/MAGEMin.v1.8.6.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[MAGEMin]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0ce514fa9a9b6fe4ec864a5ccb61ae5d4d6d48ef"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MAGEMin.download]]
    sha256 = "57d852f7c3b40f02095bd0c8819feabc4127723224741c336a639a6dadcf7ecc"
    url = "https://github.com/JuliaBinaryWrappers/MAGEMin_jll.jl/releases/download/MAGEMin-v1.8.6+0/MAGEMin.v1.8.6.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[MAGEMin]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ed43daa39f906885baf5eb8394c2d4fe2fec8164"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MAGEMin.download]]
    sha256 = "2b06d8e8edd89f3b54130a2ada41b9f2b3d4709960029f41469ac236646bbc25"
    url = "https://github.com/JuliaBinaryWrappers/MAGEMin_jll.jl/releases/download/MAGEMin-v1.8.6+0/MAGEMin.v1.8.6.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[MAGEMin]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "bcfeeb415a61289610405dd916b47f606371e72c"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MAGEMin.download]]
    sha256 = "cd752e51c2814ad69554ec89331e1da674f71407b204a87330c0535261cf6a6c"
    url = "https://github.com/JuliaBinaryWrappers/MAGEMin_jll.jl/releases/download/MAGEMin-v1.8.6+0/MAGEMin.v1.8.6.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[MAGEMin]]
arch = "i686"
git-tree-sha1 = "5b985cec038915fbbcb58990c4007eb4ff5dc8ea"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MAGEMin.download]]
    sha256 = "f131a551b43251224caf441f34d5897cd15c4f869940352716c7ede8ab8046f3"
    url = "https://github.com/JuliaBinaryWrappers/MAGEMin_jll.jl/releases/download/MAGEMin-v1.8.6+0/MAGEMin.v1.8.6.i686-linux-gnu-libgfortran5.tar.gz"
[[MAGEMin]]
arch = "i686"
git-tree-sha1 = "a2bf3fe54881968d3bba600cf5cf084c4d05ada0"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MAGEMin.download]]
    sha256 = "8e3508d548cb813cbb731db689f13a6b55524f4c5c96625388478f292715c1c5"
    url = "https://github.com/JuliaBinaryWrappers/MAGEMin_jll.jl/releases/download/MAGEMin-v1.8.6+0/MAGEMin.v1.8.6.i686-linux-musl-libgfortran5.tar.gz"
[[MAGEMin]]
arch = "i686"
git-tree-sha1 = "44bf3d92d94b9eee97f8c951a8405cc7c2691861"
libgfortran_version = "5.0.0"
os = "windows"

    [[MAGEMin.download]]
    sha256 = "eaddc5f12a62486abfefe7817f6aa4214551e8b8763053c18c2936aae5e5df45"
    url = "https://github.com/JuliaBinaryWrappers/MAGEMin_jll.jl/releases/download/MAGEMin-v1.8.6+0/MAGEMin.v1.8.6.i686-w64-mingw32-libgfortran5.tar.gz"
[[MAGEMin]]
arch = "powerpc64le"
git-tree-sha1 = "01ab315f5abfd01a9eade6e3a553d278d19e3342"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MAGEMin.download]]
    sha256 = "2720b97563175250eeb4475718823fdd4caca3e7737f5c78a09f6f43d68bbfa6"
    url = "https://github.com/JuliaBinaryWrappers/MAGEMin_jll.jl/releases/download/MAGEMin-v1.8.6+0/MAGEMin.v1.8.6.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[MAGEMin]]
arch = "x86_64"
git-tree-sha1 = "e4edccccfa019240a6ec94289e1e510f37c9fe76"
libgfortran_version = "5.0.0"
os = "macos"

    [[MAGEMin.download]]
    sha256 = "45e672acfd6a60fde1b209777a669d2efb808516429771c53da70b9a48233be0"
    url = "https://github.com/JuliaBinaryWrappers/MAGEMin_jll.jl/releases/download/MAGEMin-v1.8.6+0/MAGEMin.v1.8.6.x86_64-apple-darwin-libgfortran5.tar.gz"
[[MAGEMin]]
arch = "x86_64"
git-tree-sha1 = "dfbea3768d4a51d2ca26ddeddd13e1004265c67b"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MAGEMin.download]]
    sha256 = "7005d928097216cc8790bee2e80fc9be3756e5587b50b7d9682224c12b4e1a17"
    url = "https://github.com/JuliaBinaryWrappers/MAGEMin_jll.jl/releases/download/MAGEMin-v1.8.6+0/MAGEMin.v1.8.6.x86_64-linux-gnu-libgfortran5.tar.gz"
[[MAGEMin]]
arch = "x86_64"
git-tree-sha1 = "2e770b34bcfb8d370c1c63b7243de34ca27f6c6f"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[MAGEMin.download]]
    sha256 = "640a81cdccbf72bd4e139ab2b4f2b9aa39f714d398e2a868926b3a50d3fc850d"
    url = "https://github.com/JuliaBinaryWrappers/MAGEMin_jll.jl/releases/download/MAGEMin-v1.8.6+0/MAGEMin.v1.8.6.x86_64-linux-musl-libgfortran5.tar.gz"
[[MAGEMin]]
arch = "x86_64"
git-tree-sha1 = "bd2cf2c4663019bf7e69ad4ba1d82b97b9a12e3d"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[MAGEMin.download]]
    sha256 = "8a121a73799bdf25bc89d92b13d80da92f86c66ae5200c9605a8791a7715c567"
    url = "https://github.com/JuliaBinaryWrappers/MAGEMin_jll.jl/releases/download/MAGEMin-v1.8.6+0/MAGEMin.v1.8.6.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[MAGEMin]]
arch = "x86_64"
git-tree-sha1 = "2ffc5c3f0f481def372119e446eeb471d1a07329"
libgfortran_version = "5.0.0"
os = "windows"

    [[MAGEMin.download]]
    sha256 = "8a28fe2bb6b7eae0ecf72c76aeb698a61382cc29538715d4bc2184e67e6925ca"
    url = "https://github.com/JuliaBinaryWrappers/MAGEMin_jll.jl/releases/download/MAGEMin-v1.8.6+0/MAGEMin.v1.8.6.x86_64-w64-mingw32-libgfortran5.tar.gz"
